### ISSUE TITLE
create_barplot gives Attributerror

### ISSUE THREAD

**Issue by Asagodi** [hklarner/PyBoolNet#21] opened 2018-06-07 18:09 UTC
When running the tutorial I got the following error. The problem is in create_barplot in Basins.py, sort is called on a range object.

AttributeError                            Traceback (most recent call last)
<ipython-input-8-87dcea2fe53e> in <module>()
     74 if __name__=="__main__":
     75         create_figure_01()
---> 76         create_figure_02()
     77         create_figure_03()
     78 

<ipython-input-8-87dcea2fe53e> in create_figure_02()
     60 def create_figure_02():
     61 
---> 62         PyBoolNet.Basins.create_barplot(ATTRS, FnameImage="figure02a.pdf", Title="")
     63         PyBoolNet.Basins.create_piechart(ATTRS, FnameImage="figure02b.pdf", Title="")
     64 

~/Documents/anaconda2/envs/ml1labs/lib/python3.6/site-packages/PyBoolNet/Basins.py in create_barplot(AttrJson, FnameImage, Title, Silent)
    282 
    283         indeces = range(len(Attrs))
--> 284         indeces.sort(key=lambda i: Attrs[i]["weak_basin"]["perc"], reverse=True)
    285 
    286         y1 = [Attrs[i]["cyclefree_basin"][key] for i in indeces]

AttributeError: 'range' object has no attribute 'sort'

**Comment by hklarner** [comment] 2018-06-12 10:27
Hi Asagodi,
this seems to be a bug that is caused by the range function being an iterator in Python3 rather than a list in Python2. It might already be fixed in version 2.2.4. What version of PyBoolNet are you running?

```
>>> import PyBoolNet
>>> PyBoolNet.version()
'2.2.4'
```
Also, what code are you running ("When running the tutorial")? It seems to me like you are running code that i wrote for myself and which should not be available..

**Comment by Asagodi** [comment] 2018-06-18 09:53
I'm using version '2.2.3'.

I believe the code I used is in Tutorials/Klarner2018/, that seems to be not in the current version..

**Comment by hklarner** [comment] 2018-06-19 05:29
please install PyBoolNet 2.2.5 and try again (I meant 2.2.5 in my last comment, not 2.2.4). If it still doesn't work post the error trace again. To update to latest version download the tar file from [releases/2.2.5](https://github.com/hklarner/PyBoolNet/releases/tag/2.2.5) and run, e.g.

```
$ pip3 uninstall PyBoolNet
$ sudo pip3 install PyBoolNet-2.2.5_linux64.tar.gz
```

**Comment by Asagodi** [comment] 2018-07-07 07:57
It works now, thanks!

**Closed** 2021-09-05 12:24 UTC
Labels: solved
