### ISSUE TITLE
import Problem in python 3

### ISSUE THREAD

**Issue by RSchwieger** [hklarner/PyBoolNet#10] opened 2017-01-18 09:50 UTC
PyBoolNet.Tests.Dependencies.run() 

(Manual S.6) klappt in Python 3 nicht.

**Comment by RSchwieger** [comment] 2017-01-18 13:02
>>> PyBoolNet.Tests.Dependencies.run()
test_bnet2primes_responds (PyBoolNet.Tests.Dependencies.TestBNetToPrime) ... ok
test_layout_engines (PyBoolNet.Tests.Dependencies.TestGraphviz) ... ok
test_imagemagick_responds (PyBoolNet.Tests.Dependencies.TestImageMagick) ... ERROR
test_networkx_import (PyBoolNet.Tests.Dependencies.TestNetworkX) ... ok
test_nusmv_responds (PyBoolNet.Tests.Dependencies.TestNuSMV) ... ok
test_clasp_responds (PyBoolNet.Tests.Dependencies.TestPotassco) ... ok
test_gringo_responds (PyBoolNet.Tests.Dependencies.TestPotassco) ... ok

======================================================================
ERROR: test_imagemagick_responds (PyBoolNet.Tests.Dependencies.TestImageMagick)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/PyBoolNet/Tests/Dependencies.py", line 158, in test_imagemagick_responds
    self.assertTrue("ImageMagick" in out, msg)
TypeError: a bytes-like object is required, not 'str'

----------------------------------------------------------------------
Ran 7 tests in 0.051s

FAILED (errors=1)

**Comment by RSchwieger** [comment] 2017-01-18 13:06
>>> PyBoolNet.Tests.Dependencies.run()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'Dependencies' has no attribute 'run'

**Comment by hklarner** [comment] 2019-01-31 19:12
I am using Python3 and I can't reproduce it. Do you have problems importing with Python3? Otherwise I will close this issue.

**Comment by ritaalamino** [comment] 2019-02-05 17:07
Hi, sorry the delay. I am having a problem in import. Unfortunately I have to use windows... It can not find the Dependencies folder.

>>> import PyBoolNet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\RitaA\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PyBoolNet\__init__.py", line 6, in <module>
    import PyBoolNet.Attractors
  File "C:\Users\RitaA\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PyBoolNet\Attractors.py", line 9, in <module>
    import PyBoolNet.FileExchange
  File "C:\Users\RitaA\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PyBoolNet\FileExchange.py", line 9, in <module>
    import PyBoolNet.PrimeImplicants
  File "C:\Users\RitaA\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PyBoolNet\PrimeImplicants.py", line 4, in <module>
    import PyBoolNet.QuineMcCluskey
  File "C:\Users\RitaA\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PyBoolNet\QuineMcCluskey.py", line 12, in <module>
    with open(fname_nusmvkeywords) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\RitaA\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\PyBoolNet\\Dependencies\\nusmvkeywords.json'

**Closed** 2019-02-06 06:59 UTC
Labels: bug
